services:
  - name: hockerman-com-web
    type: web
    env: docker
    dockerfilePath: ./web/Dockerfile
    region: ohio
    plan: starter
    branch: master
    numInstances: 1
    healthCheckPath: /
    domains:
      - hockerman.com
      - www.hockerman.com
    envVars:
      - key: ROOT_URL
        value: "https://hockerman.com"
      - fromGroup: twitter-hockerman-com
      - fromGroup: hockerman-com-super-secret
      - fromGroup: supabase-hockerman-com
      - fromGroup: spotify-auth-hockerman-com