export const ALL_EXPERIENCE = [
  {
    borderColor: "#fcd34d",
    company: "IndyHackers",
    companyHref: "https://www.indyhackers.org",
    location: "Indianapolis, IN",
    positions: [{ title: "Board Member", years: "2024-now" }],
    resume: [
      "IndyHackers strives to help tech people in Indiana grow by fostering community connections and celebrating individual successes.",
    ],
    tags: ["community"],
    tech: [],
  },
  {
    borderColor: "#f97316",
    company: "Take The Reins",
    location: "Noblesville, IN",
    positions: [{ title: "Volunteer Web Engineer", years: "2024-now" }],
    resume: [
      "I began working with Take The Reins in early 2024 to help revitalize their web and social media presence.",
    ],
    tags: ["community"],
    tech: [],
  },
  {
    borderColor: "#34d399",
    company: "Trava",
    companyHref: "https://travasecurity.com",
    location: "Indianapolis, IN",
    positions: [{ title: "Senior Software Engineer", years: "2023-now" }],
    resume: [
      "Architected, built, maintained, and evolved an array of TypeScript and Golang-based systems powering cybersecurity scanning for our customers, leveraging technologies such as Temporal, React, and open source scanning tools to identify vulnerabilities.",
      "Balanced the prioritization of customer needs, business requirements, product evolution, and technical debt to meaningfully move the product suite forward.",
      "Mentored a team of entry and mid-level engineers, assisting with architecture, decision making, documentation, career development, and implementation.",
    ],
    tags: ["professional"],
    tech: [
      "React",
      "Node.js",
      "TypeScript",
      "Temporal",
      "Go",
      "Google Cloud",
      "Kubernetes",
      "Firebase",
    ],
  },
  {
    borderColor: "#7c3aed",
    company: "Women Investors Network",
    companyHref: "https://womeninvestorsnetwork.org",
    location: "Indianapolis, IN",
    positions: [{ title: "Volunteer Web Engineer", years: "2019-now" }],
    resume: [
      "Planned & implemented back-of-house technical systems, including online accounts, mailing lists, domain management, and the primary marketing website.",
    ],
    tags: ["community"],
    tech: [],
  },
  {
    borderColor: "#1d4ed8",
    company: "TechPoint",
    companyHref: "https://techpoint.org",
    location: "Indianapolis, IN",
    positions: [{ title: "Volunteer Engineer", years: "2018-now" }],
    resume: [
      "Every year, the Xtern program matches hundreds of applicants for central Indiana technology internships to companies. Since ~2018, this matching has been automated using software I help execute and maintain.",
    ],
    tags: ["community"],
    tech: [],
  },
  {
    borderColor: "#fb923c",
    company: "Cloudflare",
    companyHref: "https://cloudflare.com",
    location: "Remote",
    positions: [{ title: "Systems Engineer", years: "2021-2023" }],
    resume: [
      "Architected & implemented new API and domains-facing platform features for enterprise customers including opt-in domain security enhancements and API access over mTLS.",
      "Modernized dozens of legacy workloads from traditional servers to Kubernetes.",
      "Responded to high severity on-call incidents affecting millions of customers and internet users, implementing observability and alerting improvements across our services.",
    ],
    tags: ["professional"],
    tech: ["Go", "PHP", "Postgres", "Kubernetes"],
  },
  {
    borderColor: "#f1f5f9",
    company: "Practical Creatives",
    location: "Indianapolis, IN",
    positions: [{ title: "Founder", years: "2021-2023" }],
    resume: [
      "Practical Creatives was an Etsy store focused on the design, production, and sale of bespoke & useful 3D printed things.",
    ],
    tags: ["projects"],
    tech: ["Shapr3D", "Fusion 360", "3D Printing", "Etsy", "SEO"],
  },
  {
    borderColor: "#c084fc",
    company: "Structural",
    companyHref: "https://structural.com",
    location: "Indianapolis, IN",
    positions: [
      { title: "Senior Software Engineer", years: "2020-2021" },
      { title: "Software Engineer", years: "2016-2020" },
    ],
    resume: [
      "Shipped countless product features spanning Structural’s Typescript & Node.JS backend and React frontend, including user sign-in and authorization, bulk user importing, business metrics tracking, the in-app admin panel, and more.",
      "Owned and maintained all cloud deployed assets on AWS, evolving our deployment strategy over the years from a single EC2 instance, to adopting Docker, Kubernetes, and eventually AWS ECS.",
      "Acted as engineering point-of-contact on security reviews and compliance, including four years of successful SOC-2 Type II audits.",
      "Led the implementation of a variety of system monitoring and instrumentation capabilities, including alerting, refining our on-call procedures, logging, and distributed tracing, generally with Datadog.",
    ],
    tags: ["professional"],
    tech: [
      "TypeScript",
      "Node.js",
      "AWS",
      "MongoDB",
      "Kubernetes",
      "ECS",
      "Go",
      "React",
      "Next.js",
    ],
  },
  {
    borderColor: "#15803d",
    company: "Indy Tech Fellowship",
    companyHref: "https://techpoint.org",
    location: "Indianapolis, IN",
    positions: [
      { title: "Board Chair, Curriculum", years: "2016-2018" },
      { title: "Member", years: "2016-2018" },
    ],
    resume: [
      "After graduating from Purdue, I joined on to help build the first class of TechPoint's Tech Fellowship program; a two year post-grad program for tech workers in Indianapolis focusing on continuing education, social connections, and community outreach.",
      "During my service, I helped build the foundations for the Tech Fellowship's curriculum program, including planning technology-oriented workshops for other members and running lunch-and-learns and fireside chats with local business leaders.",
    ],
    tags: ["community"],
    tech: [],
  },
  {
    borderColor: "#fbbf24",
    company: "Purdue University",
    companyHref: "https://purdue.edu",
    location: "West Lafayette, IN",
    positions: [
      { title: "B.S. Computer Science", years: "2012-2015" },
      { title: "Minor, Organizational Leadership", years: "" },
    ],
    resume: [
      "Served as Vice President and President of Purdue's ACM Special Interest Group for Application Development (SIGAPP).",
    ],
    tags: ["edu"],
    tech: ["Android", "iOS", "C++", "Python", "JavaScript"],
  },
  {
    borderColor: "#ef4444",
    company: "Yelp",
    companyHref: "https://yelp.com",
    location: "San Francisco, CA",
    positions: [{ title: "Software Engineering Intern", years: "2015" }],
    resume: [
      "Optimized log search times in a MySQL-sourced data pipeline for business analytics, and engineered a mapping/filtering system to flag and censor personally identifiable information within the pipeline.",
    ],
    tags: ["professional"],
    tech: ["Python"],
  },
  {
    borderColor: "#22d3ee",
    company: "Genesys",
    companyHref: "https://genesys.com",
    location: "Indianapolis, IN",
    positions: [{ title: "Software Engineering Intern", years: "2014" }],
    resume: [
      "Shipped an end-to-end system which scanned PDF documents, applied optical character recognition and barcode scanning, and indexed the results in Elasticsearch.",
    ],
    tags: ["professional"],
    tech: ["Java"],
  },
  {
    borderColor: "#1d4ed8",
    company: "Xtern",
    companyHref: "https://techpoint.org",
    location: "Indianapolis, IN",
    positions: [{ title: "Member", years: "2014" }],
    resume: [
      "Alongside my internship with Genesys, I participated in the first class of TechPoint's Xtern program.",
    ],
    tags: ["community"],
    tech: [],
  },
];
