name: Deploy
on:
  push:
    branches: [master]
jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: chrislennon/action-aws-cli@v1.1
      - run: npm install
      - run: npm run build
      - run: next export
      - run: aws s3 sync ./out s3://mhoc-co-website
      - run: rm -rf ./out
      - run: aws cloudfront create-invalidation --distribution-id EO1O33M2R2N09 --paths "/*"